[workspace]
resolver = "3"
members = [
    "cometbft-p2p",
    "ethers-iqkms",
    "iq-crypto",
    "iqkms",
    "iqkms-ethereum",
    "iqkms-proto",
    "iqkms-signing",
    "iqkms-types",
    "iqkmsd"
]
