[package]
name = "iqkms-signing"
version = "0.0.0"
edition = "2021"

[dependencies]
signatory = { version = "0.26", features = ["secp256k1"] }
rand_core = { version = "0.6", features = ["getrandom"] }

# optional dependencies
base16ct = { version = "0.1", optional = true, features = ["alloc"] }
sec1 = { version = "0.3", optional = true, default-features = false, features = ["point"] }
sha3 = { version = "0.10", optional = true, default-features = false }

[features]
ethereum = ["base16ct", "sec1", "sha3"]
