[package]
name = "ethers-iqkms"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
ethers-core = { git = "https://github.com/gakonst/ethers-rs.git" }
ethers-signers = { git = "https://github.com/gakonst/ethers-rs.git" }
iqkms = { version = "0", path = "../iqkms", features = ["ethereum"] }
tracing = "0.1.37"
