name: iq-crypto

on:
  pull_request:
    paths:
      - ".github/workflows/iq-crypto.yml"
      - "iq-crypto/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: iq-crypto

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.64.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo install cargo-hack
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --exclude-features getrandom,std

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.64.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --release
