name: iqkms

on:
  pull_request:
    paths:
      - ".github/workflows/iqkms.yml"
      - "Cargo.*"
      - "iqkms/**"
      - "iqkms-proto/**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: iqkms

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.85 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: sudo apt-get install protobuf-compiler
      - run: cargo test
      - run: cargo test --release
