name: iqkms

on:
  pull_request:
    paths:
      - ".github/workflows/iqkms.yml"
      - "iqkms"
      - "iqkms-proto"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: iqkms

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  # TODO(tarcieri): run tests in CI
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.63.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: sudo apt-get install protobuf-compiler
      - run: cargo build
      - run: cargo build --release
