name: signing

on:
  pull_request:
    paths:
      - ".github/workflows/signing.yml"
      - "iqkms-signing"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: iqkms-signing

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.63.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --release
