name: signing

on:
  pull_request:
    paths:
      - ".github/workflows/signing.yml"
      - "Cargo.*"
      - "iq-crypto/**"
      - "iqkms-signing/**"
      - "iqkms-types/**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: iqkms-signing

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.70 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      # TODO(tarcieri): - run: cargo test
      - run: cargo test --all-features
      # TODO(tarcieri): - run: cargo test --release
      - run: cargo test --all-features --release
